# 'path' should be an absolute path (relative paths have issues)
path: /Users/unswaccount/Documents/Studying/Year 2/VIP - Robo-Re-Cycle/Object Detection Data/computerVision_v3.0_annotatedDataSet
# 'train' and 'val' are relative to 'path'
train: obj_train_data/images
val: obj_train_data/images

# Classes
names:
  0: screw-hole
  1: torx-screw