# 'path' should be an absolute path (relative paths have issues)
# refers to the path of the directory that stores both your images AND the corresponding labels

path: /Users/unswaccount/Documents/Studying/Year 2/VIP - Robo-Re-Cycle/Object Detection Data/screwsAndHoles datasets/computerVision_v6.0_annotatedDataSet/obj_train_data
# 'train' and 'val' are relative to 'path'
train: images
val: images

# Classes
names:
  0: screw-hole
  1: torx-screw


# Within your file system, YOLOv8 expects the directory at "path" to look like:
# <main directory>                      refers to the directory provided by "path"
#     images                            make sure this directory is called images
#         <all of your images>
#     labels                            make sure this directory is called labels
#         <all of your corresponding labels"



# If you are still unsure as to how training a model works, I would recommend watching 
# and copying the tutorial mentioned in trainModel.py (https://www.youtube.com/watch?v=m9fH9OWn8YM).
# This tutorial goes through the steps of data collection, data annotation, 
# organising your data and training your model.